# Generated by Django 3.1.5 on 2021-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('birthday', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('grade', models.SmallIntegerField(blank=True, choices=[(5, 'Excelent'), (4, 'Good'), (3, 'Satisfactory'), (2, 'Unsatisfactory')], db_index=True, null=True)),
            ],
        ),
    ]
